services:
  backend:
    container_name: java-backend-pos
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8083:8083"
    volumes:
      - .:/app                           # bind mount your whole project
      - ~/.gradle:/home/gradle/.gradle  # use host Gradle cache
    working_dir: /app
    command: ./gradlew bootRun
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/umerautos
      SPRING_DATASOURCE_USERNAME: springstudent
      SPRING_DATASOURCE_PASSWORD: springstudent
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: springstudent
      MYSQL_DATABASE: umerautos
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
